# Generated by Django 3.2.5 on 2022-04-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_created=True, verbose_name='Дата старта')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('properties', models.JSONField(verbose_name='Фильтр свойств')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='номер телефона клиента')),
                ('code', models.IntegerField(verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=50, verbose_name='тег (произвольная метка)')),
                ('timezone', models.IntegerField(verbose_name='часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_created=True, verbose_name='дата и время создания')),
                ('state', models.CharField(max_length=50, verbose_name='статус отправки')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notification', verbose_name='id рассылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users', verbose_name='id клиента')),
            ],
        ),
    ]
